### ISSUE TITLE
SiteMap Graphic Boundaries

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/tbnmc-compliance-assessment-2020#4]
@fawda123 Not a critical issue, but the sitemap.png boundaries should reflect the TBNMC/FDEP recognized bay segment boundaries. LTB's boundary looks like it includes 'Boca Ciega Bay - South.' Technically, for the TBNMC and RA reporting the following segments are recognized: Old Tampa Bay, Hillsborough Bay, Middle Tampa Bay, Lower Tampa Bay and the 'Remainder of LTB' which includes Boca Ciega Bay- South, Terra Ceia Bay and the Manatee River bay segments. The EPCHC stations within the LTB segment are used to assess compliance in both the LTB and the 'Remainder of LTB' segments.

**Comment by fawda123** [comment]
Thanks Ed, can you point me to where the correct shapefile is at?  The one used in the plot comes from one I've got in the tbeptools package (https://tbep-tech.github.io/tbeptools/reference/tbseg.html).

**Comment by esherwoo77** [comment]
Here’s the major basin boundary file that we use: T:\05_GIS\BOUNDARIES\TBEP_Major_Basins_Correct_Projection.shp <file://TBEPSERVER/tbepdrive/05_GIS/BOUNDARIES/TBEP_Major_Basins_Correct_Projection.shp>  .

 

OTB Segment  = Coastal OTB basin 

HB Segment = Coastal HB, Hillsborough River & Alafia River basins

MTB Segment = Coastal MTB, Little Manatee River basins

LTB Segment = Coastal LTB basin

‘Remainder of LTB’ Segment = Lower BCB, Coastal TCB and Manatee River basins

 

Upper BCB is an orphan in the TBNMC assessments. 

 

Ed Sherwood

Executive Director

Tampa Bay Estuary Program

263 13th Ave. South

St. Petersburg, FL 33701

Ph:   <tel:(727)%20893-2765> (727) 893-2765

Fax:  <tel:(727)%20893-2767> (727) 893-2767

 <mailto:esherwood@tbep.org> esherwood@tbep.org

 <http://www.tbep.org/> www.tbep.org

 



 

All government correspondence is subject to the public records law.

**Comment by fawda123** [comment]
Okay, I cheated and just replaced the polygons with line boundaries similar to the older versions.
![image](https://user-images.githubusercontent.com/3086881/78074463-c4974200-7370-11ea-8a4c-3b5257321205.png)
