### ISSUE TITLE
review updated draft

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/tbnmc-compliance-assessment-2020#7]
@emseabee I incorporated your edits and recompiled the document with current figures and tables.  Please have a look at the current draft here https://tbep-tech.github.io/tbnmc-compliance-assessment/

**Comment by emseabee** [comment]
@fawda123 a bunch of the links point to redirects from the old tbeptech.org website. i thought i updated them, but must not? teach me the trick?

**Comment by fawda123** [comment]
Aw snap, yea I still see four links to the old domain. You updated some, so did I, but we missed a few.  It should update if you just change the links and commit as you did before.  I'd do it myself but I don't know where these docs live (RA docs mostly, I found the 2009 addendum in our library , but that's it).
