### ISSUE TITLE
Fig. 5: Update graphic with 2020 data (when available) and new goal

### ISSUE THREAD

**Issue by esherwoo77** [tbep-tech/tbnmc-compliance-assessment-2020#9]
Here are the data used to develop the original SigmaPlot graphic:

Year | Acres | Hectares
-- | -- | --
1950 | 40420.00 | 16357.39
1982 | 21650.00 | 8761.44
1988 | 23285.00 | 9423.11
1990 | 25226.00 | 10208.60
1992 | 25753.00 | 10421.87
1994 | 26518.00 | 10731.45
1996 | 26916.00 | 10892.52
1999 | 24841.00 | 10052.80
2001 | 26078.00 | 10553.39
2004 | 27021.00 | 10935.01
2006 | 28299.00 | 11452.20
2008 | 29647.00 | 11997.72
2010 | 32897.00 | 13312.94
2012 | 34642.00 | 14019.27
2014 | 40294.71 | 16306.69
2016 | 41655.16 | 16857.25
2018 | 40651.55 | 16451.10

**Comment by fawda123** [comment]
Putting this here for now until we're ready to share: https://github.com/tbep-tech/SOB-figures/commit/fdeb988cae9f3aab3d4095aa6906aef4745834fa

**Comment by fawda123** [comment]
@emseabee just updated the seagrass figure, should in the document https://github.com/tbep-tech/tbnmc-compliance-assessment/blob/master/figure/seagrasscov.png
